###

POST https://localhost:{{PORT}}/reservation
Content-Type: application/json

{
  "date"  : "2024-02-09",
  "name"  : "Stefano Cerruti",
  "email"  : "stefano.cerruti@outlook.com",
  "quantity"  : {{$random.integer(1,10)}}
}

###

GET https://localhost:{{PORT}}/reservation