###Book Stefano

POST https://localhost:{{PORT}}/reservation
Content-Type: application/json

{
  "date"  : "2024-02-09",
  "name"  : "Stefano Cerruti",
  "email"  : "stefano.cerruti@outlook.com",
  "quantity"  : {{$random.integer(1,10)}}
}

###Book Polonzo

POST https://localhost:{{PORT}}/reservation
Content-Type: application/json

{
  "date"  : "2024-02-09",
  "name"  : "Cavallo Polonzo",
  "email"  : "polonzomolofoloppo@outlook.com.polonzo",
  "quantity"  : {{$random.integer(1,10)}}
}

###Get All Reservations

GET https://localhost:{{PORT}}/reservation

###Get 2024/02/09 Reservations
GET https://localhost:{{PORT}}/reservation/2024/02/09
Accept: application/json
