### POST
< {%
    request.variables.set("PORT", "7045")
    
%}

POST https://localhost:{{PORT}}/reservation
Content-Type: application/json

{
  "date"  : "2024-01-26",
  "name"  : "Stefano Cerruti",
  "email"  : "stefano.cerruti@outlook.com",
  "quantity"  : {{$random.integer(1,10)}}
}

